export const DOSSIER_TOKENS_PER_UNIT = 450;
export const LOOKALIKE_TOKENS_PER_UNIT = 1200;
export const DOMAIN_TAKEDOWN_TOKENS_PER_UNIT = 200;

export const NIOS_MODELS = ['TE-926', 'TE-1516', 'TE-1526', 'TE-2326', 'TE-4126'];
export const UDDI_SIZES = ['3XS', '2XS', 'XS', 'S', 'M', 'L', 'XL'];

export const hardwareSkuMapping = {
  '3XS': { default: 'B1-105-HW-AC', alternatives: ['B1-212-HW-AC'] },
  '2XS': { default: 'B1-105-HW-AC', alternatives: ['B1-212-HW-AC'] },
  'XS': { default: 'B1-212-HW-AC', alternatives: ['B1-105-HW-AC'] },
  'S': { default: 'B1-212-HW-AC', alternatives: ['B1-105-HW-AC'] },
  'M': { default: 'B1-212-HW-AC', alternatives: ['B1-105-HW-AC'] },
  'L': { default: 'B1-212-HW-AC', alternatives: ['B1-105-HW-AC'] },
  'XL': { default: 'B1-212-HW-AC', alternatives: ['B1-105-HW-AC'] },
  'TE-926': { default: 'TE-906-HW-2AC', alternatives: ['TE-906-HW-AC'] },
  'TE-1516': { default: 'TE-1506-HW-AC', alternatives: ['TE-1506-HW-DC', 'TE-1506-10GE-HW-AC', 'TE-1506-10GE-HW-DC'] },
  'TE-1526': { default: 'TE-1606-HW-AC', alternatives: ['TE-1606-HW-DC', 'TE-1606-10GE-HW-AC', 'TE-1606-10GE-HW-DC'] },
  'TE-2326': { default: 'TE-2306-HW-AC', alternatives: ['TE-2306-HW-DC', 'TE-2306-10GE-HW-AC', 'TE-2306-10GE-HW-DC'] },
  'TE-4126': { default: 'TE-4106-HW-AC', alternatives: ['TE-4106-HW-DC', 'TE-4106-10GE-HW-AC', 'TE-4106-10GE-HW-DC'] },
  'TE-825': { default: 'TE-805-HW-AC', alternatives: [], locked: true },
  'TE-2215': { default: 'TE-2205-HW-AC', alternatives: [], locked: true },
  'TE-4015': { default: 'TE-4005-HW-AC', alternatives: ['TE-4005-10G-HW-AC'], locked: true },
  'TE-4025': { default: 'TE-4005-HW-AC', alternatives: ['TE-4005-10G-HW-AC'], locked: true },
};

export const defaultAssetConfigData = {
  assetsPerWorker: 4.0,
  override: false,
  knowledgeWorkersOverride: 0,
  verifiedPerWorker: 0.86,
  unverifiedPerWorker: 3.14,
  totalAssets: 0,
  verifiedAssets: 0,
  unverifiedAssets: 0,
  growthBufferEnabled: false,
  growthBuffer: 0.15,
  tdCloudEnabled: false,
  overrideAssetsPerKW: false,
  customAssetsPerKW: 0,
  overrideVerifiedPerKW: false,
  customVerifiedPerKW: 0,
  overrideUnverifiedPerKW: false,
  customUnverifiedPerKW: 0,
};

export const defaultReportingData = {
  enabled: false,
  collapsed: true,
  securityEventsOverride: false,
  securityEventsPercent: 5,
  securityEventsTokens: 0,
  reportingGrowthBufferEnabled: false,
  reportingGrowthBuffer: 15,
  securityEventsEnabled: true,
  totalReportingTokens: 0,
  verifiedAssets: 0,
  unverifiedAssets: 0,
};

export const defaultUDDIData = {
  enabled: false,
  mode: 'native',
  knowledgeWorkers: 0,
  devicesPerUser: 2.5,
  isIPv6InScope: false,
  activeIPs: 0,
  assets: 0,
  dhcpPercent: 80,
  staticPercent: 20,
  enableDNSManagement: true,
  enableDNSProtocol: true,
  staticClients: 0,
  servers: [],
  dynamicClients: 0,
  enableIPAMManagement: true,
  enableDHCPManagement: true,
  enableDHCPProtocol: true,
  dhcpClients: 0,
  sitesBranches: 0,
  networksPerSite: 0,
  daysPerMonth: 31,
  workdaysPerMonth: 22,
  secondsPerWorkdayHrs: 9,
  qpdPerActiveIP: 3500,
  dnsRecsPerIP: 2.0,
  dnsRecsPerLease: 3.0,
  bufferOverhead: 15,
  dhcpHaFo: true,
  defaultLeaseTimeHr: 1.0,
  growthBuffer: 20,
  ddiObjects: 0,
  calculatedActiveIPs: 0,
  discoveredAssets: 0,
  totalManagementTokens: 0,
  totalMonthlyLogs: 0,
};
