import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Check, X, Loader2, Upload, FileText, ChevronDown, ChevronUp, RefreshCw, Edit3, CheckCheck } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import * as XLSX from 'xlsx';
import { useToast } from "@/hooks/use-toast";
import { useDiscovery } from "@/contexts/DiscoveryContext";
import { getApiUrl } from "@/lib/queryClient";

interface MeetingNotesAIProps {
  customerName?: string;
  opportunityName?: string;
}

export function MeetingNotesAI({ customerName = '', opportunityName = '' }: MeetingNotesAIProps) {
  const { meetingNotes, setMeetingNotes, setAnswer, contextFields, setContextField, answers, notes, questions, sizingSummary, platformMode } = useDiscovery();
  const [isProcessing, setIsProcessing] = useState(false);
  const [matches, setMatches] = useState([]);
  const [uploadedFileName, setUploadedFileName] = useState(null);
  const [isExpanded, setIsExpanded] = useState(false);
  const [generating, setGenerating] = useState({});
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const fileInputRef = useRef(null);
  const textareaRef = useRef(null);
  const { toast } = useToast();

  // Summary field config - short, descriptive bullet point style
  const summaryFields = [
    { key: 'environment', label: "Customer's Current Environment", placeholder: "• IPAM, DNS, DHCP details\n• Products being used\n• Vendor/technology specifics\n• Locations & integrations" },
    { key: 'outcomes', label: "Customer's Desired Project Outcomes", placeholder: "• Project goals\n• Pain points to resolve\n• Timeline & phases\n• Project sponsors" },
    { key: 'endState', label: "Customer's Target End State", placeholder: "• Target architecture\n• Migration path\n• DDI design features\n• Integration requirements" },
  ];

  // Auto-expand textarea when typing
  useEffect(() => {
    if (meetingNotes.length > 0 && !isExpanded) {
      setIsExpanded(true);
    }
  }, [meetingNotes]);

  // Auto-generate summaries on load if meeting notes exist and summaries are empty
  useEffect(() => {
    if (!hasAutoGenerated && meetingNotes.trim().length > 100) {
      const hasEmptySummaries = summaryFields.some(f => !contextFields[f.key]?.trim());
      if (hasEmptySummaries) {
        handleGenerateAll();
        setHasAutoGenerated(true);
      }
    }
  }, [meetingNotes, hasAutoGenerated]);

  // Generate a single summary field
  const handleGenerate = async (contextType) => {
    if (!meetingNotes.trim() && Object.keys(answers).length === 0) {
      toast({ title: "No data", description: "Enter meeting notes or answer discovery questions first", variant: "destructive" });
      return;
    }
    setGenerating(prev => ({ ...prev, [contextType]: true }));
    try {
      const res = await fetch(getApiUrl('/api/generate-context'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contextType, answers, notes, meetingNotes,
          customerName, opportunityName, platformMode,
          sizingSummary: {
            totalIPs: sizingSummary?.totalIPs,
            siteCount: sizingSummary?.siteCount,
            totalObjects: sizingSummary?.totalObjects,
            dnsSiteCount: sizingSummary?.dnsSiteCount,
            platformMode: sizingSummary?.platformMode,
          },
        }),
      });
      if (!res.ok) throw new Error('Generation failed');
      const data = await res.json();
      setContextField(contextType, data.summary);
    } catch (err) {
      console.error('Context generation failed:', err);
      toast({ title: "Generation failed", description: "Could not generate summary. Try again.", variant: "destructive" });
    } finally {
      setGenerating(prev => ({ ...prev, [contextType]: false }));
    }
  };

  // Generate all summaries
  const handleGenerateAll = async () => {
    if (!meetingNotes.trim() && Object.keys(answers).length === 0) {
      toast({ title: "No data", description: "Enter meeting notes or answer discovery questions first", variant: "destructive" });
      return;
    }
    for (const field of summaryFields) {
      await handleGenerate(field.key);
    }
    toast({ title: "Summaries generated", description: "All context summaries have been updated" });
  };

  const handleAnalyze = async () => {
    if (!meetingNotes.trim()) { toast({ title: "No meeting notes", description: "Please enter meeting notes to analyze", variant: "destructive" }); return; }
    setIsProcessing(true);
    try {
      const response = await fetch(getApiUrl('/api/analyze-notes'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ notes: meetingNotes }) });
      if (!response.ok) throw new Error('Failed to analyze meeting notes');
      const data = await response.json();
      const aiMatches = (data.matches || []).map(match => {
        const question = questions.find(q => q.id === match.questionId);
        return { questionId: match.questionId, section: question?.section || 'Unknown', question: question?.question || '', extractedAnswer: match.answer, confidence: match.confidence === 'high' ? 0.9 : 0.7 };
      });
      setMatches(aiMatches);
      toast({ title: "Analysis complete", description: `Found ${aiMatches.length} potential matches` });
    } catch (error) {
      console.error('Error analyzing notes:', error);
      toast({ title: "Analysis failed", description: "Failed to analyze meeting notes. Please try again.", variant: "destructive" });
    } finally { setIsProcessing(false); }
  };

  const handleAccept = (questionId) => { const match = matches.find(m => m.questionId === questionId); if (match) setAnswer(questionId, match.extractedAnswer); setMatches(prev => prev.filter(m => m.questionId !== questionId)); };
  const handleReject = (questionId) => { setMatches(prev => prev.filter(m => m.questionId !== questionId)); };
  const handleAcceptAll = () => { matches.forEach(match => setAnswer(match.questionId, match.extractedAnswer)); setMatches([]); };

  const handleFileUpload = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const ext = file.name.split('.').pop()?.toLowerCase();
    if (!['txt', 'csv', 'xls', 'xlsx'].includes(ext)) { toast({ title: "Unsupported file type", description: "Please upload a .txt, .csv, .xls, or .xlsx file", variant: "destructive" }); return; }
    try {
      let text = '';
      if (ext === 'csv' || ext === 'txt') {
        text = await file.text();
      } else {
        const buffer = await file.arrayBuffer();
        const workbook = XLSX.read(buffer, { type: 'array' });
        text = workbook.SheetNames.map(name => {
          const csv = XLSX.utils.sheet_to_csv(workbook.Sheets[name], { blankrows: false });
          return workbook.SheetNames.length > 1 ? `=== ${name} ===\n${csv}` : csv;
        }).join('\n\n');
      }
      setMeetingNotes(text);
      setUploadedFileName(file.name);
      setIsExpanded(true);
      setHasAutoGenerated(false); // Allow auto-gen on new file
      toast({ title: "Document uploaded", description: `Loaded content from ${file.name}` });
    } catch (error) {
      toast({ title: "Error reading file", description: "Failed to extract text.", variant: "destructive" });
    }
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const isAnyGenerating = Object.values(generating).some(Boolean);

  return (
    <div className="space-y-4">
      {/* Compact Meeting Notes Paste Box */}
      <Card>
        <CardHeader className="pb-2">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Meeting Notes
              {uploadedFileName && <Badge variant="outline" className="text-xs ml-2">{uploadedFileName}</Badge>}
            </CardTitle>
            <div className="flex items-center gap-2">
              <input ref={fileInputRef} type="file" accept=".txt,.csv,.xls,.xlsx" onChange={handleFileUpload} className="hidden" data-testid="input-file-upload" />
              <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => fileInputRef.current?.click()} data-testid="button-upload-document">
                <Upload className="h-3 w-3 mr-1" />Upload
              </Button>
              <Button variant="outline" size="sm" className="h-7 text-xs" onClick={handleAnalyze} disabled={!meetingNotes.trim() || isProcessing} data-testid="button-analyze-notes">
                {isProcessing ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Sparkles className="h-3 w-3 mr-1" />}
                Extract Answers
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="relative">
            <Textarea 
              ref={textareaRef}
              value={meetingNotes} 
              onChange={e => setMeetingNotes(e.target.value)} 
              placeholder="Paste meeting notes, call transcripts, or discovery conversations here..."
              className={`resize-none transition-all duration-200 text-sm ${isExpanded ? 'min-h-[120px]' : 'min-h-[60px]'}`}
              onFocus={() => setIsExpanded(true)}
              data-testid="input-meeting-notes" 
            />
            {meetingNotes.length > 0 && (
              <Button variant="ghost" size="sm" className="absolute bottom-1 right-1 h-6 text-xs opacity-60 hover:opacity-100" onClick={() => setIsExpanded(!isExpanded)}>
                {isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Matched Answers — compact table layout */}
      {matches.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                Extracted Answers
                <Badge variant="secondary" className="text-xs">{matches.length}</Badge>
              </CardTitle>
              <div className="flex items-center gap-2">
                <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => setMatches([])} data-testid="button-reject-all">
                  <X className="h-3 w-3 mr-1" />Reject All
                </Button>
                <Button size="sm" className="h-7 text-xs" onClick={handleAcceptAll} data-testid="button-accept-all">
                  <CheckCheck className="h-3 w-3 mr-1" />Accept All
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-0 px-0">
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b bg-muted/40">
                    <th className="text-left px-3 py-1.5 font-semibold text-muted-foreground w-[1%] whitespace-nowrap">#</th>
                    <th className="text-left px-3 py-1.5 font-semibold text-muted-foreground w-[12%] whitespace-nowrap">Section</th>
                    <th className="text-left px-3 py-1.5 font-semibold text-muted-foreground">Question</th>
                    <th className="text-left px-3 py-1.5 font-semibold text-muted-foreground">Answer</th>
                    <th className="text-center px-3 py-1.5 font-semibold text-muted-foreground w-[1%] whitespace-nowrap">Conf</th>
                    <th className="text-center px-3 py-1.5 font-semibold text-muted-foreground w-[1%] whitespace-nowrap">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {matches.map((match, idx) => (
                    <tr key={match.questionId} className="border-b last:border-0 hover:bg-muted/30 transition-colors" data-testid={`match-${match.questionId}`}>
                      <td className="px-3 py-2 text-muted-foreground tabular-nums">{idx + 1}</td>
                      <td className="px-3 py-2">
                        <Badge variant="outline" className="text-[10px] py-0 whitespace-nowrap">{match.section}</Badge>
                      </td>
                      <td className="px-3 py-2">
                        <TooltipProvider>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <span className="font-medium truncate block max-w-[220px] cursor-default">{match.question}</span>
                            </TooltipTrigger>
                            <TooltipContent side="top" className="max-w-xs text-xs bg-popover text-popover-foreground border border-border">
                              {match.question}
                            </TooltipContent>
                          </Tooltip>
                        </TooltipProvider>
                      </td>
                      <td className="px-3 py-2 max-w-[260px]">
                        {answers[match.questionId] && (
                          <div className="text-muted-foreground line-through text-[10px] leading-tight mb-0.5 truncate">{answers[match.questionId]}</div>
                        )}
                        <div className="text-primary font-medium truncate" title={match.extractedAnswer}>{match.extractedAnswer}</div>
                      </td>
                      <td className="px-3 py-2 text-center">
                        <span className={`inline-flex items-center gap-1 font-medium ${
                          match.confidence > 0.8 ? 'text-green-600 dark:text-green-400' : 'text-amber-600 dark:text-amber-400'
                        }`}>
                          <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${
                            match.confidence > 0.8 ? 'bg-green-500' : 'bg-amber-500'
                          }`} />
                          {Math.round(match.confidence * 100)}%
                        </span>
                      </td>
                      <td className="px-3 py-2">
                        <div className="flex items-center justify-center gap-1">
                          <TooltipProvider>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button size="sm" variant="default" className="h-6 w-6 p-0" onClick={() => handleAccept(match.questionId)} data-testid={`button-accept-${match.questionId}`}>
                                  <Check className="h-3 w-3" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent className="text-xs">Accept</TooltipContent>
                            </Tooltip>
                          </TooltipProvider>
                          <TooltipProvider>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button size="sm" variant="outline" className="h-6 w-6 p-0" onClick={() => handleReject(match.questionId)} data-testid={`button-reject-${match.questionId}`}>
                                  <X className="h-3 w-3" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent className="text-xs">Reject</TooltipContent>
                            </Tooltip>
                          </TooltipProvider>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* AI-Generated Context Summaries - 3 Column Layout */}
      <Card>
        <CardHeader className="pb-2">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm flex items-center gap-2">
              <Edit3 className="h-4 w-4" />
              Context Summaries
              <span className="text-xs font-normal text-muted-foreground">(editable)</span>
            </CardTitle>
            <Button variant="outline" size="sm" className="h-7 text-xs" onClick={handleGenerateAll} disabled={isAnyGenerating} data-testid="button-generate-all">
              {isAnyGenerating ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <RefreshCw className="h-3 w-3 mr-1" />}
              Analyze All
            </Button>
          </div>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
            {summaryFields.map(field => (
              <div key={field.key} className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">{field.label}</h4>
                  <Button variant="ghost" size="sm" className="h-5 w-5 p-0" onClick={() => handleGenerate(field.key)} disabled={generating[field.key]} data-testid={`generate-${field.key}`}>
                    {generating[field.key] ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3 text-muted-foreground hover:text-primary" />}
                  </Button>
                </div>
                <Textarea 
                  value={contextFields[field.key] || ''} 
                  onChange={e => setContextField(field.key, e.target.value)} 
                  placeholder={field.placeholder}
                  className="min-h-[140px] text-xs resize-y leading-relaxed"
                  data-testid={`context-${field.key}`} 
                />
              </div>
            ))}
          </div>
          <p className="text-xs text-muted-foreground mt-3">
            Summaries are auto-generated from meeting notes and discovery answers. Edit directly to refine.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
